# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = { fsType = "tmpfs"; options = [ "defaults" "size=2G" "mode=755" ]; };
    "/boot" = { device = "/dev/disk/by-uuid/F80E-3594"; fsType = "vfat"; };
  };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/41407c27-1829-4cc4-bf34-d4167dabe1e1";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "compress-force=zstd" ];
    };

  fileSystems."/persistent" =
    {
      device = "/dev/disk/by-uuid/41407c27-1829-4cc4-bf34-d4167dabe1e1";
      fsType = "btrfs";
      options = [ "subvol=persistent" "noatime" "compress-force=zstd" ];
    };

  fileSystems."/etc/nixos" =
    {
      device = "/persistent/persistent/Projects/flakes-final";
      fsType = "none";
      options = [ "bind" ];
    };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
